# Form implementation generated from reading ui file '.\marketplace.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import webbrowser
from PyQt6 import QtCore, QtGui, QtWidgets
from bs4 import BeautifulSoup
import requests as req
import webbrowser


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(307, 410)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 36))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 50, 56, 17))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 70, 56, 17))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 231, 16))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 307, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.startup()

    def startup(self):
        url = "https://maarasteh.github.io/beagleeditor/marketplace.html"
        response = req.get(url)
        html_content = response.content
        soup = BeautifulSoup(html_content, 'html.parser')
        plugins_name = soup.find_all('h4')
        for plugin_name in plugins_name:
            mod_plugin_name1 = str(plugin_name).replace("<h4>", "")
            mod_plugin_name2 = mod_plugin_name1.replace("</h4>", "")
            self.final_plugin_name = mod_plugin_name2.replace(":", "")
            self.label_2.setText(self.final_plugin_name)
        links = soup.find_all("a")
        for link in links:
            if str(link).startswith("https://github.com/") and "releases" in link:
                self.pushButton.clicked.connect(self.download)
            elif str(link).startswith("https://github.com/") and "blob" in link:
                self.pushButton_2.clicked.connect(self.open_github)

    def download(self):
        r = req.get(f"https://github.com/MaArasteh/beagleeditor-plugins/releases/download/v1/{self.final_plugin_name}.py", allow_redirects=True)
        open(f"{self.final_plugin_name}.py", 'wb').write(r.content)

    def open_github(self):
        webbrowser.open(f"github.com/MaArasteh/beagleeditor-plugins/releases/blob/main/{self.final_plugin_name}.py")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "BeagleEditor Plugins Marketplace"))
        self.pushButton.setText(_translate("MainWindow", "Download"))
        self.pushButton_2.setText(_translate("MainWindow", "GitHub"))
        self.label_2.setText(_translate("MainWindow", "Plugin Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
